name: Build

env:
    GLUALINT_VERSION: 1.26.0
    NEODOC_VERSION: 0.1.6

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download & extract glualint
              run: |
                wget -c https://github.com/FPtje/GLuaFixer/releases/download/${GLUALINT_VERSION}/glualint-${GLUALINT_VERSION}-x86_64-linux.zip -O glualint.zip
                unzip -u glualint.zip
                rm glualint.zip

            - name: Check code with glualint
              run: ./glualint .
    # docs:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4

    #         - name: Setup .NET Core
    #           run: sudo apt-get install -y mono-complete

    #         - name: Download & extract neodoc
    #           run: |
    #             wget -c https://github.com/TTT-2/NeoDoc/releases/download/v${NEODOC_VERSION}/NeoDoc-v${NEODOC_VERSION}.zip -O neodoc.zip
    #             unzip -u neodoc.zip
    #             rm neodoc.zip
      
    #         - name: Check code with neodoc
    #           run: mono NeoDoc.exe .
