name: 'Changelog'
on:
    pull_request

jobs:
    changelog:
        runs-on: ubuntu-latest
        steps:
            - uses: dangoslen/changelog-enforcer@v3
              with:
                changeLogPath: 'CHANGELOG.md'
                skipLabels: 'skip-changelog'
